// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/afrizal423/Golang-Perpustakaan-Restful-API/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// IDendaRepository is an autogenerated mock type for the IDendaRepository type
type IDendaRepository struct {
	mock.Mock
}

// CountDendaByID provides a mock function with given fields: id
func (_m *IDendaRepository) CountDendaByID(id string) (int64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CountDendaByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDenda provides a mock function with given fields: denda
func (_m *IDendaRepository) CreateDenda(denda *domain.Denda) error {
	ret := _m.Called(denda)

	if len(ret) == 0 {
		panic("no return value specified for CreateDenda")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Denda) error); ok {
		r0 = rf(denda)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDenda provides a mock function with given fields: id
func (_m *IDendaRepository) DeleteDenda(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDenda")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllDenda provides a mock function with no fields
func (_m *IDendaRepository) GetAllDenda() ([]domain.Denda, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllDenda")
	}

	var r0 []domain.Denda
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Denda, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Denda); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Denda)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDendaByID provides a mock function with given fields: id
func (_m *IDendaRepository) GetDendaByID(id string) (*domain.Denda, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDendaByID")
	}

	var r0 *domain.Denda
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Denda, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Denda); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Denda)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDenda provides a mock function with given fields: denda
func (_m *IDendaRepository) UpdateDenda(denda *domain.Denda) error {
	ret := _m.Called(denda)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDenda")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Denda) error); ok {
		r0 = rf(denda)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDendaRepository creates a new instance of IDendaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDendaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDendaRepository {
	mock := &IDendaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
