// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/afrizal423/Golang-Perpustakaan-Restful-API/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// IPeminjamanRepository is an autogenerated mock type for the IPeminjamanRepository type
type IPeminjamanRepository struct {
	mock.Mock
}

// CountPeminjamanByID provides a mock function with given fields: id
func (_m *IPeminjamanRepository) CountPeminjamanByID(id string) (int64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CountPeminjamanByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePeminjaman provides a mock function with given fields: peminjaman
func (_m *IPeminjamanRepository) CreatePeminjaman(peminjaman *domain.Peminjaman) error {
	ret := _m.Called(peminjaman)

	if len(ret) == 0 {
		panic("no return value specified for CreatePeminjaman")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Peminjaman) error); ok {
		r0 = rf(peminjaman)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePeminjaman provides a mock function with given fields: id
func (_m *IPeminjamanRepository) DeletePeminjaman(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePeminjaman")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPeminjaman provides a mock function with no fields
func (_m *IPeminjamanRepository) GetAllPeminjaman() ([]domain.Peminjaman, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPeminjaman")
	}

	var r0 []domain.Peminjaman
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Peminjaman, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Peminjaman); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Peminjaman)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailPeminjaman provides a mock function with given fields: id
func (_m *IPeminjamanRepository) GetDetailPeminjaman(id string) (*domain.Peminjaman, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailPeminjaman")
	}

	var r0 *domain.Peminjaman
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Peminjaman, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Peminjaman); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Peminjaman)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPeminjamanByID provides a mock function with given fields: id
func (_m *IPeminjamanRepository) GetPeminjamanByID(id string) (*domain.Peminjaman, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPeminjamanByID")
	}

	var r0 *domain.Peminjaman
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Peminjaman, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Peminjaman); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Peminjaman)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePeminjaman provides a mock function with given fields: peminjaman
func (_m *IPeminjamanRepository) UpdatePeminjaman(peminjaman *domain.Peminjaman) error {
	ret := _m.Called(peminjaman)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePeminjaman")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Peminjaman) error); ok {
		r0 = rf(peminjaman)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPeminjamanRepository creates a new instance of IPeminjamanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPeminjamanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPeminjamanRepository {
	mock := &IPeminjamanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
